import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./providers/ThemeProvider";
import { ReduxProvider } from "./providers/ReduxProvider";
import { ThemeToggle } from "../components/ThemeToggle";
import OAuthListener from "../components/OAuthListener";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <ThemeProvider>
            <header className="flex items-center justify-between px-6 py-4 bg-indigo-600 text-white">
              <Link href="/" className="font-semibold text-white">Admin Panel</Link>
              <div className="flex items-center gap-4">
                <Link href="/auth/login" className="text-indigo-100 text-sm">Sign in</Link>
                <ThemeToggle />
              </div>
            </header>
            <OAuthListener />
            {children}
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
